"""initial schema

Revision ID: e4cea7074163
Revises: 0001_initial
Create Date: 2026-06-09 17:52:07.442069

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("crawl_runs", "started_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("crawl_runs", "new_listings", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("crawl_runs", "total_scraped", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "crawl_runs", "errors", existing_type=sa.TEXT(), type_=sa.String(), nullable=True
    )
    op.alter_column(
        "crawl_runs", "triggered_by", existing_type=sa.VARCHAR(length=40), nullable=True
    )
    op.add_column("deployments", sa.Column("status", sa.String(), nullable=True))
    op.alter_column(
        "deployments",
        "id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "deployments", "deployed_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "deployments", "deployed_by", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("deployments", "notes", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("deployments", "image_tag")
    op.drop_column("deployments", "is_current")
    op.drop_column("deployments", "rollback_of")
    op.alter_column("listings", "price", existing_type=sa.VARCHAR(length=80), nullable=True)
    op.alter_column("listings", "location", existing_type=sa.VARCHAR(length=200), nullable=True)
    op.alter_column("listings", "url", existing_type=sa.TEXT(), type_=sa.String(), nullable=True)
    op.alter_column("listings", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("listings", "notified", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("listings", "first_seen", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("listings", "last_seen", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("listings", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("listings", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("listings", "last_seen", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("listings", "first_seen", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("listings", "notified", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("listings", "description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("listings", "url", existing_type=sa.String(), type_=sa.TEXT(), nullable=False)
    op.alter_column("listings", "location", existing_type=sa.VARCHAR(length=200), nullable=False)
    op.alter_column("listings", "price", existing_type=sa.VARCHAR(length=80), nullable=False)
    op.add_column(
        "deployments", sa.Column("rollback_of", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "deployments", sa.Column("is_current", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "deployments",
        sa.Column("image_tag", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.alter_column("deployments", "notes", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "deployments", "deployed_by", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "deployments", "deployed_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "deployments",
        "id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("deployments", "status")
    op.alter_column(
        "crawl_runs", "triggered_by", existing_type=sa.VARCHAR(length=40), nullable=False
    )
    op.alter_column(
        "crawl_runs", "errors", existing_type=sa.String(), type_=sa.TEXT(), nullable=False
    )
    op.alter_column("crawl_runs", "total_scraped", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("crawl_runs", "new_listings", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "crawl_runs", "started_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
